services:
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - products-service
      - billing-service

  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=users-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "8001:8001"
    volumes:
      - users-data:/data
    depends_on:
      - otel-collector

  products-service:
    build:
      context: .
      dockerfile: products-service/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=products-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "8002:8002"
    volumes:
      - products-data:/data
    depends_on:
      - otel-collector

  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=billing-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "8004:8004"
    volumes:
      - billing-data:/data
    depends_on:
      - users-service
      - products-service
      - payment-service
      - otel-collector

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    volumes:
      - payments-data:/data
    ports:
      - "8003:8003"
    depends_on:
      - bank-service
      - otel-collector
    environment:
      - BANK_SERVICE_HOST=bank-service:50051
      - OTEL_SERVICE_NAME=payment-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

  bank-service:
    build:
      context: .
      dockerfile: bank-service/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=bank-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    ports:
      - "50051:50051"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.150.1
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./configs/otelcol-config.yaml:/etc/otelcol-contrib/config.yaml

volumes:
  products-data:
  payments-data:
  users-data:
  billing-data: