apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rs-flux-instance.yaml
  - rs-flux-operator.yaml
  - rs-cert-manager.yaml
  - rs-opentelemtry-operator.yaml
  - rs-services.yaml
  - rs-collector.yaml
