apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: collector-resources
  namespace: flux-system
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: opentelemetry-operator
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: opentelemetry-operator
      namespace: opentelemetry-operator-system
      ready: true
  resources:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: grafana-cloud
        namespace: workshop
      type: Opaque
      stringData:
        GRAFANA_CLOUD_OTLP_ENDPOINT: "__GRAFANA_CLOUD_OTLP_ENDPOINT__"
        GRAFANA_CLOUD_INSTANCE_ID: "__GRAFANA_CLOUD_INSTANCE_ID__"
        GRAFANA_CLOUD_API_KEY: "__GRAFANA_CLOUD_API_KEY__"

    - apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      metadata:
        name: workshop
        namespace: workshop
      spec:
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.145.0
        envFrom:
          - secretRef:
              name: grafana-cloud
        config:
          extensions:
            basicauth/grafana_cloud:
              client_auth:
                username: "${env:GRAFANA_CLOUD_INSTANCE_ID}"
                password: "${env:GRAFANA_CLOUD_API_KEY}"

          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318

          processors:
            batch: {}
            memory_limiter:
              check_interval: 1s
              limit_percentage: 75
              spike_limit_percentage: 15

          exporters:
            debug:
              verbosity: detailed
            otlphttp/grafana_cloud:
              endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
              auth:
                authenticator: basicauth/grafana_cloud

          service:
            extensions: [basicauth/grafana_cloud]
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlphttp/grafana_cloud]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlphttp/grafana_cloud]
              logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [debug, otlphttp/grafana_cloud]

    - apiVersion: opentelemetry.io/v1alpha1
      kind: Instrumentation
      metadata:
        name: python-instrumentation
        namespace: workshop
      spec:
        exporter:
          endpoint: http://workshop-collector:4318
        env:
        propagators:
          - tracecontext
          - baggage
        python:
          env:
            - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
              value: 'true'
            - name: OTEL_PYTHON_TRACES_AUTO_INSTRUMENTATION_ENABLED
              value: 'true'
            - name: OTEL_PYTHON_METRICS_AUTO_INSTRUMENTATION_ENABLED
              value: 'true'

    - apiVersion: opentelemetry.io/v1alpha1
      kind: Instrumentation
      metadata:
        name: go-instrumentation
        namespace: workshop
      spec:
        exporter:
          endpoint: http://workshop-collector:4317
        env:
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_LOG_LEVEL
            value: debug
        propagators:
          - tracecontext
          - baggage
