apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: grafana
  namespace: flux-system
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: flux-instance
      namespace: flux-system
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: tempo
      namespace: flux-system
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: grafana
        namespace: observability
      spec:
        interval: 1h
        type: oci
        url: oci://ghcr.io/grafana-community/helm-charts
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: grafana
        namespace: observability
      spec:
        interval: 1h
        releaseName: grafana
        chart:
          spec:
            chart: grafana
            version: '11.2.*'
            sourceRef:
              kind: HelmRepository
              name: grafana
            interval: 30m
        values:
          replicas: 1
          headlessService: false
          automountServiceAccountToken: true
          autoscaling:
            enabled: false
          deploymentStrategy:
            type: Recreate
          testFramework:
            enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
          ingress:
            enabled: false
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          persistence:
            type: pvc
            enabled: true
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            size: 20Gi

          grafana.ini:
            server:
              root_url: "http://grafana.localhost:8080"

          # Administrator credentials when not using an existing secret (see below)
          adminUser: admin
          adminPassword: strongpassword
    - apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: grafana
        namespace: observability
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`grafana.localhost`)
            kind: Rule
            services:
              - name: grafana
                port: 80